// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "reto-softteck",
    "version": "1"
  },
  "paths": {
    "/crearJedi": {
      "post": {
        "summary": "crearJedi",
        "description": "",
        "operationId": "crearJedi.post./crearJedi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/listarJedis": {
      "get": {
        "summary": "listarJedis",
        "description": "",
        "operationId": "listarJedis.get./listarJedis",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/traducirData": {
      "get": {
        "summary": "traducirData",
        "description": "",
        "operationId": "traducirData.get./traducirData",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};